### ISSUE TITLE
How to load the package in Maple?

### ISSUE THREAD

**Issue by DZaiger** [jmokland/schubert#2]
Hello, I have a small question about loading the package. I added the path in my MacBook to schubertlib in HomeLib and libname, and try with(schubert) command. But what I got is "Error, invalid input: with expects its 1st argument, pname, to be of type {`module`, package}, but received schubert". 

I have also tried "LibraryTools:-ShowContents(libname)" command, and it seems that "schubert.m" file cannot be read. Could you tell me how to load this package? I'm using Maple 2023. Thank you!

**Comment by jmokland** [comment]
Hi! 

The next thing to try is the incantation
```
kernelopts('readdotm'=true):
```
if that's not enough then the next this is the rebuilding from the schubertlib/README.

**Comment by DZaiger** [comment]
Thank you very much for your kind reply. I see, I rebuilt the package and it seems to work now. Thank you!
